### ISSUE TITLE
Readline infects users with the GNU virus

### ISSUE THREAD

**Issue by snunez1** [mmontone/duologue#2]
`readline` is released under the GNU license, which is prohibited in most commercial environments. Would it be possible to use [libedit](https://www.thrysoee.dk/editline/) or [linenoise ](https://github.com/antirez/linenoise)instead?

**Comment by mmontone** [comment]
Ah. Good point. I'll have a look soon.

**Comment by mmontone** [comment]
I see there's this library: https://linedit.common-lisp.dev/ (MIT license)

I'll see if I can replace readline with that.

**Comment by mmontone** [comment]
For my future reference:

```lisp
(defun list-completer (options)
  (lambda (str editor)
    (declare (ignore editor))
    (let ((ls (remove-if-not (lambda (option)
			       (str:starts-with? str option))
			     options)))
      (values ls (length ls)))))

(linedit:linedit :complete (list-completer '("foo" "bar" "baz")))
```

**Comment by snunez1** [comment]
I've looked at that before. The latest version is at https://github.com/sharplispers/linedit, however it's abandoned over at sharplispers too, and [doesn't run on MS Windows](https://github.com/sharplispers/linedit/issues/7) because of [issues with the upstream osicat](https://github.com/osicat/osicat/issues), that also seems abandoned (pull requests languishing since 2020). 

What problem is this library trying to solve? If it's editing the input before being submitted, wouldn't slime/emacs handle that? If  it's editing in a terminal, perhaps including the line editng library could be optional (or conditional, e.g. #-win32)? I suspect most folks will be using slime and not a terminal to provide input.

**Comment by mmontone** [comment]
It is just using readline as a completion backend.
I think the fastest fix for your use case would be to make the readline backend optional; the library can be used without readline completion.
So, the library would have duologue.asd, that doesn't bind to any completion backend; and optional ASDF systems like, duologue-readline.asd and duologue-lineedit.asd .
How does that sound to you?

**Comment by snunez1** [comment]
That sounds like the simplest way forward. Completion isn't that important for the kinds of simple input I need; certainly not worth the effort of fixing both osicat & linedit, and having different backends would allow independent development of features, e.g. masking input for password entry, or perhaps a CL based completion library (now that would be interesting!).

**Comment by mmontone** [comment]
Good. I'll implement the separation then.

**Comment by mmontone** [comment]
@snunez1 I've made the separation. Please let me know if it works for you.

**Comment by snunez1** [comment]
It works just fine, thanks.
