### ISSUE TITLE
&optional and &key in same function lambda list

### ISSUE THREAD

**Issue by snunez1** [mmontone/duologue#3]
Just noting that SBCL considers this a style-warning. Practical Common Lisp suggests it's [not a good idea](https://gigamonkeys.com/book/functions.html) as well:

> Combining &optional and &key parameters yields surprising enough results that you should probably avoid it altogether.

**Comment by mmontone** [comment]
Yes, I saw that yesterday when I made some changes to the code. But would have to think about how to change the interface.

**Comment by mmontone** [comment]
"Problem" here is that I liked that you could say: `(prompt)` and you get a prompt, without specifying a message.

Maybe I should overcome that, and just make the prompt message a required argument.

**Comment by snunez1** [comment]
Can't you just have &key but then not provide any when you call the function?

**Comment by mmontone** [comment]
You mean use a `:msg` key parameter?
And then use: `(prompt :msg "My message: " ...)`.

I could, but I like it better `(prompt "My message: " ...)`

**Comment by snunez1** [comment]
That's what I meant.
```
(defun foo (&key foo bar baz (msg "this is a message"))
  msg)
```
and call it without a prompt
```
(foo)
"this is a message"
```
I'm not aware of any way to get what you want, but I'd like to have a pattern for it myself.

What message do you propose to print if one isn't supplied?

**Comment by mmontone** [comment]
I think I'm just gonna make the message a required argument. Using prompts
without a message is not very useful I imagine, so...

**Comment by mmontone** [comment]
I've made message argument a required argument.

This also removes all the warnings, I believe.

Let me know if it looks good in your opinion.

**Comment by snunez1** [comment]
Looking good. No problems encountered.

**Comment by mmontone** [comment]
I think it is fine. Closing.
