### ISSUE TITLE
*query-io* vs. *standard-input/output*

### ISSUE THREAD

**Issue by snunez1** [mmontone/duologue#4]
Is there a reason for using `*standard-input/output*` over `*query-io*`? I'd have thought the latter to be more in line with the intended purpose of querying the user for input than `*standard-*` streams. From the CLHS section on [standard streams](https://www.cs.cmu.edu/Groups/AI/html/cltl/clm/node183.html):

> The value of *query-io* is a stream to be used when asking questions of the user. The question should be output to this stream, and the answer read from it. When the normal input to a program may be coming from a file, questions such as ``Do you really want to delete all of the files in your directory?'' should nevertheless be sent directly to the user; and the answer should come from the user, not from the data file. For such purposes *query-io* should be used instead of *standard-input* and *standard-output*. *query-io* is used by such functions as yes-or-no-p.

**Comment by mmontone** [comment]
I was not aware of `*query-io*`. I can look.

**Comment by mmontone** [comment]
Using `*query-io*` now ...
