### ISSUE TITLE
Idiomatic way of ensuring valid input?

### ISSUE THREAD

**Issue by snunez1** [mmontone/duologue#5]
Is there an example of idiomatically _ensuring_ valid input from the user?

**Sample use-case**

I want the user to enter an integer between 1 and 100. Ideally I could pass a type spec to `prompt-integer`, e.g.

`(prompt-integer "Enter an integer between 1 and 100: " :type '(integer 1 100))`.

If the user entered, say, 200, the system would loop around again and ask for valid input, e.g.:

`Error: 200 is not between 1 and 100, please enter again: `.

What's the best way to achieve this?

**Comment by mmontone** [comment]
I had to push a fix.

duologue uses clavier library for validation.

```lisp
(prompt-integer "Enter an integer between 1 and 100: "
			 :validator (clavier:fn (lambda (x)
					  (< 0 x 100)) "")
			 :if-invalid (lambda (&rest args)
				       (declare (ignore args))
				       (say "Should be between 0 and 100")))
```

I don't like the api. It should be possible to just use without clavier and lambda, like this:

```lisp
(prompt-integer "Enter an integer between 1 and 100: "
			 :validator (lambda (x) (< 0 x 100))
			 :if-invalid "Should be between 0 and 100")
```

I can look to improve it ...

**Comment by mmontone** [comment]
That `:type` argument you are using gives me an idea to perhaps add a `:type` parameter to `prompt`.
And you could be able to just call `(duologue:prompt "Enter beteween 1 and 100: " :type '(integer 1 100) :if-invalid "Should be between 1 and 100")`

**Comment by mmontone** [comment]
Sorry for the mess. This is an old and unmaintained library of mine.

**Comment by mmontone** [comment]
This works after my last commit:

```lisp
(prompt-integer "Enter an integer between 1 and 100: "
			 :validator (lambda (x)
					  (< 0 x 100))
			 :if-invalid "Should be between 0 and 100")
```

**Comment by snunez1** [comment]
Just as an FYI, there's a maintained user input validation library, [ratify](https://github.com/shinmera/ratify).

**Comment by mmontone** [comment]
I've added a `:type` parameter: 

```lisp
(prompt "Enter a number:" :parser #'parse-integer :type '(integer 0 100))
```

But a Unit Test Suit is missing. I don't like programming like I'm doing now.

**Comment by snunez1** [comment]
All, good, and I appreciate the updates. I'm fine with waiting. I also like to program carefully...

**Comment by snunez1** [comment]
I can't say that in my application usage I've exhaustively tested this function, but so far in about a dozen different places, I haven't encountered an error.

Do you want to close this?

**Comment by mmontone** [comment]
Ah. Good to know. Yes.
