### ISSUE TITLE
Prompt behaviour

### ISSUE THREAD

**Issue by snunez1** [mmontone/duologue#8]
I've noticed something odd about the prompt. If you end the `msg` with a `:`, the output is requested on the same line, which is the expected behavour. However if you don't, the input is prompted for after a newline is printed by duologue.

Is this by design?

**Comment by mmontone** [comment]
Mm.. I don't think so . I'll look ..

**Comment by mmontone** [comment]
I'm not sure yet why, but in the meantime you can add a space at the end:
`(duologue:prompt "write please ")`

And no newline is printed.

**Comment by mmontone** [comment]
I think this is related to `say` behaviour, that `prompt` uses in some cases:

```
(when (or newline
              (not (cl-ppcre:scan "[ \\t](\\e\\[\\d+(;\\d+)*m)?\\Z" datum)))
      (terpri))
```

I sincerely don't remember why that's there now.

**Comment by snunez1** [comment]
Putting a space at the end seems to fix it, thanks.
