### ISSUE TITLE
duologue-readline license gpl3+ or mit?

### ISSUE THREAD

**Issue by jgarte** [mmontone/duologue#9]
Hi, should this line be changed to mit like the rest of the code or is it really gpl3+?

https://github.com/mmontone/duologue/blob/master/duologue-readline.asd#L4

I ask because I'm trying to package the library for [Guix](https://guix.gnu.org/).

**Comment by mmontone** [comment]
I think it needs to be GPL because readline library is GPL.

**Comment by mmontone** [comment]
That's why I created a separate ASDF system for the readline code.

**Comment by jgarte** [comment]
Thanks for the update. Ok, I updated the Guix package to include both.
